### ISSUE TITLE
Things to do before 3.11 beta

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#320]
3.11 beta is on 2022-05-06 https://peps.python.org/pep-0664/
before then we want to do the following:

#### Quickening

- [x] Perform quickening in place
- [ ] Lazily create `co_code`
- [ ] Don't use temporary bytes object when unmarshaling

#### Extra superinstructions
- [x] Remove most `PUSH_NULL`s
- [ ] Restore `LOAD_FAST__LOAD_ATTR_VAUE`
- [ ] Add `RESUME__LOAD_FAST` superinstruction
- [ ] Maybe add some sort of extended jump instruction(s)

#### Fix up `CALL` instructions

This still needs some more investigation

- [ ] Specialize for `METH_METHOD` correctly
- [ ] Reduce overhead of `PRECALL`
- [ ] Sort out calls to Python classes

#### Why has startup slowed down?

https://github.com/python/cpython/pull/31872 might help.

**Comment by markshannon** [comment]
Removed "Add instrumentation to replace tests for tracing on each bytecode" See https://github.com/faster-cpython/ideas/issues/112#issuecomment-1087368415

**Comment by markshannon** [comment]
3.11 beta has been released.

We did improve Windows performance quite a lot.
Other than that, it seems like we didn't get much of the above done, but we looked into them all, and most turned out not to be that important to get done for 3.11
