### ISSUE TITLE
Set up a cron job to run benchmarks

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#386]
This is an aggregate issue.  Each sub-task will be done separately:

* [x] faster-cpython/tools#31
* [x] faster-cpython/tools#57
* [x] set up a GitHub bot user (`faster-cpython-bot`, `faster.cpython@gmail.com`)
* [x] faster-cpython/tools#60
* [x] fixes for running as a bot user
* [x] faster-cpython/tools#61
* [x] add a cron job (on portal host or via GH action)

**Comment by ericsnowcurrently** [comment]
I ended up needing the upload command anyway.

**Comment by ericsnowcurrently** [comment]
I set up the cron job today (to run every Sunday).

**Comment by ericsnowcurrently** [comment]
I'll close this next week, once we've verified that the cron job ran correctly.

**Comment by ericsnowcurrently** [comment]
Yep. 🙂
